title: Hu Longtao's Homepage
page-top-title: Hu Longtao
top-section-bg-text: Live in the moment
home-subtitle: Hu Longtao&ensp;|&ensp;胡茏涛
copyright-text: '&copy; YourHu Longtaoname 2023-2025. All Rights Reserved.'
